---
# volumen persistente
apiVersion: v1
kind: PersistentVolume #espacio en el que vivira
metadata:
  name: pv-act3-mysql
spec: #Configuración de lo que va a contruir a nivel de disco
  storageClassName: mysql-storage
  capacity:
    storage: 10Gi # Capacidad
  accessModes:
    - ReadWriteMany # Lectura y escritura
  hostPath:
    path: "/mnt/mysql" # Lugar donde guardara los datos

---
# reclamo de volumen
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-act3-mysql
spec:
  storageClassName: mysql-storage
  accessModes:
    - ReadWriteMany
  resources: #Configuración de lo que va a reclamar
    requests:
      storage: 5Gi

---
# storage class

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-storage
  namespace: axel-2-namespace
provisioner: kubernetes.io/no-provisioner # no-provisioner -> Entorno de de infraestructura local
reclaimPolicy: Retain # Que realizara con mis datos // preserva la integridad de mis datos
volumeBindingMode: WaitForFirstConsumer

---
# configmap mysql
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: mysql-config
data:
  MYSQL_DATABASE: "db1mysql"
  MYSQL_ROOT_PASSWORD: "1234"

---
#deploy mysql
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-ac3-deploy
spec:
  selector:
    matchLabels:
      app: mysql-ac3-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-ac3-deploy
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: mysql-config
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-deploy-a3
      volumes:
        - name: mysql-deploy-a3
          persistentVolumeClaim:
            claimName: pvc-act3-mysql

---
#service mysql

apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-ac3-mysql
spec:
  selector:
    app: mysql-ac3-deploy
  ports:
    - port: 5303
      targetPort: 3306
  type: LoadBalancer
